# Generated by Django 4.1.3 on 2022-12-28 03:21

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MXEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[950, 670], upload_to='productosimg/')),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('stado', models.CharField(choices=[('1', 'Activa'), ('2', 'Cerrada')], default='1', max_length=1)),
                ('num_posibilidades', models.IntegerField(default=1)),
                ('num_boletos', models.IntegerField(default=10000)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rifa.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('mx_stado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rifa.mxestados')),
            ],
        ),
        migrations.CreateModel(
            name='Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('seleccionado', models.BooleanField(default=False)),
                ('fecha_seleccionado', models.DateTimeField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pagado', models.DateTimeField(blank=True, null=True)),
                ('ganador', models.BooleanField(default=False)),
                ('principal', models.BooleanField(default=False)),
                ('secundario', models.BooleanField(default=False)),
                ('id_principal', models.IntegerField(blank=True, default=0, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rifa.participante')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones', models.CharField(default='Condicion', max_length=255)),
                ('premio', models.CharField(default='20,000 MXN', max_length=200)),
                ('rifa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa')),
            ],
        ),
    ]
