# Generated by Django 4.1.3 on 2023-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_rifa_precio_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('banco', models.CharField(max_length=50)),
                ('tipo_transaccion', models.CharField(choices=[('1', 'Trasferencia y Cajero'), ('2', 'OXXO y Seven')], max_length=1)),
            ],
        ),
    ]
