# Generated by Django 4.1.3 on 2022-11-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='stado',
            field=models.CharField(choices=[('1', 'Activa'), ('2', 'Cerrada')], default='1', max_length=1),
        ),
    ]
