# Generated by Django 4.1.3 on 2023-01-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_cuentabanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='num_cuenta',
            field=models.CharField(max_length=16),
        ),
    ]
