# Generated by Django 4.1.3 on 2022-12-07 22:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0005_alter_rifa_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='productosimg/'),
        ),
    ]
