# Generated by Django 4.1.3 on 2022-12-07 22:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[950, 670], upload_to='productosimg/'),
        ),
    ]
