# Generated by Django 4.1.3 on 2022-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='num_posibilidades',
            field=models.IntegerField(default=1),
        ),
    ]
